### PR TITLE
validate profiles

### LINKED ISSUE #19: Scary error when forgetting `client_id` or `client_secret`
At the moment if by any chance `client_id` or `client_secret` are `nil` you would eventually get this error:

```
java.lang.IllegalArgumentException
No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil 
```

Which is kind of cryptic, and the thing is that since most of the times `client_id` `client_secret` would passed in (I guess) often as environment variables, it's probably easy to forget they are not set locally, and thus spending a lot of time trying to figure out what's wrong (as it happened to me). Some basic validation at least on these two fields would be enough imho.

### PR DESCRIPTION
**Pull request by AndreaCrotti**
Closes #19 

This only gets called if you use the ring handler though, but that's supposed to be the entry point anyway?

### CODE REVIEW

File: src/ring/middleware/oauth2.clj [hunk 1]
```diff
@@ -90,7 +90,15 @@
 (defn- parse-redirect-url [{:keys [redirect-uri]}]
   (.getPath (java.net.URI. redirect-uri)))
 
+(defn validate-profile
```
Comment (weavejester) [inline src/ring/middleware/oauth2.clj]: Rather than packing an assert and a predicate together, you could write:

```clojure
(defn- valid-profile? [{:keys [client-id client-secret]}]
  (and (some? client-id) (some? client-secret)))
```

And then in `wrap-oauth2`, add a precondition:

```clojure
{:pre [(every? valid-profile? profiles)]}

**Comment by weavejester** [comment]
Thanks! Could you fix the tests, and add a test to check that an `AssertionError` is thrown when the profiles lack the correct keys?

File: test/ring/middleware/oauth2_test.clj [hunk 2]
```diff
@@ -2,10 +2,10 @@
   (:require [clj-http.fake :as fake]
             [clj-time.core :as time]
             [clojure.string :as str]
-            [clojure.test :refer :all]
+            [clojure.test :refer [deftest is testing]]
```
Comment (AndreaCrotti) [inline test/ring/middleware/oauth2_test.clj]: this is just my personal taste to make the linter happy and not have magic symbols, but I can revert if you don't like it

**Comment by AndreaCrotti** [comment]
I've added a test now @weavejester , the tests were actually passing the problem was simply that the valid-profile? was not returning a boolean, and now it's fixed.

A couple of extra things:
- not too happy about the name `valid-profile?` since we are really just checking a couple of keys, I guess it can be invalid for many other reasons, but not sure how else we can call it?
  If all the fields should actually not be `nil` anyway I could just add a check for all of them, and then maybe `valid-profile?` makes more sense?
- I noticed in the test file quite a few `let` without body or unused bindings like `response (handler request)`is that something I could fix as well or should I just leave it?

File: test/ring/middleware/oauth2_test.clj (hunk 2 above)
Comment (weavejester) [reply test/ring/middleware/oauth2_test.clj]: Please revert the change. I don't mind commits that fix formatting, but they should be reserved for their own PRs. By adding formatting changes to other commits we just pollute the diff and make it hard to understand what's changed.

However, feel free to send me another PR with *just* formatting changes, and I'll merge it in.

File: test/ring/middleware/oauth2_test.clj [hunk 3]
```diff
@@ -2,10 +2,10 @@
...
             [ring.middleware.oauth2 :as oauth2 :refer [wrap-oauth2]]
-            [ring.mock.request :as mock]
             [ring.middleware.params :refer [wrap-params]]
+            [ring.mock.request :as mock]
```
Comment (weavejester) [inline test/ring/middleware/oauth2_test.clj]: See comment about formatting changes.

File: test/ring/middleware/oauth2_test.clj [hunk 4]
```diff
@@ -142,9 +150,9 @@
   (fake/with-fake-routes
     {"https://example.com/oauth2/access-token"
      (wrap-params (fn [req]
-                     (let [params (get-in req [:params])]
-                        (is (contains-many? params "client_id" "client_secret"))
-                       token-response)))}
+                    (let [params (get-in req [:params])]
```
Comment (weavejester) [inline test/ring/middleware/oauth2_test.clj]: See comment about formatting changes.

File: test/ring/middleware/oauth2_test.clj [hunk 5]
```diff
@@ -49,6 +49,14 @@
         location  (get-in response [:headers "Location"])]
     (is (.startsWith ^String location "https://example.com/oauth2/authorize?business_partner_id=XXXX&"))))
 
+(deftest test-missing-client-id
+  (let [profile  (assoc test-profile
```
Comment (weavejester) [inline test/ring/middleware/oauth2_test.clj]: We probably want to test multiple values, e.g.

```clojure
(deftest test-missing-fields
  (let [profile (assoc test-profile :client-id nil)]
    (is (thrown? AssertionError (wrap-oauth2 token-handler {:test profile}))))
  (let [profile (assoc test-profile :client-secret nil)]
    (is (thrown? AssertionError (wrap-oauth2 token-handler {:test profile})))))

File: test/ring/middleware/oauth2_test.clj [hunk 6]
```diff
@@ -49,6 +49,14 @@
...
+                        :client-id
+                        nil)]
+
+    (assert (is (thrown? AssertionError
```
Comment (weavejester) [inline test/ring/middleware/oauth2_test.clj]: The `assert` here is unnecessary.

**Comment by weavejester** [comment]
Almost perfect. Can you update the commit message to follow these [seven rules](https://chris.beams.io/posts/git-commit/#seven-rules). So perhaps something like:

    Assert client-id and client-secret are not nil

    Improves error messages when the client-id or client-secret is missing
    from the profile.

    Fixes #19.

**Comment by AndreaCrotti** [comment]
Done 👍
