### PR TITLE
Fix #27 by using java.util.Date for storing expiration time

### LINKED ISSUE #27: No reader function for tag object when using cookie store
If I have in my ring configuration

```(assoc-in site-defaults [:session :store] (cookie-store {:key "a very secret cookie key"}))```

I get the error:

```
java.lang.RuntimeException: No reader function for tag object
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:801)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:783)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:549)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.lang.EdnReader.readString(EdnReader.java:67)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at ring.middleware.session.cookie$serialize.invokeStatic(cookie.clj:69)
	at ring.middleware.session.cookie$serialize.invoke(cookie.clj:68)
	at ring.middleware.session.cookie$seal.invokeStatic(cookie.clj:75)
	at ring.middleware.session.cookie$seal.invoke(cookie.clj:72)
	at ring.middleware.session.cookie.CookieStore.write_session(cookie.clj:91)
	at ring.middleware.session$bare_session_response.invokeStatic(session.clj:52)
	at ring.middleware.session$bare_session_response.invoke(session.clj:43)
	at ring.middleware.session$session_response.invokeStatic(session.clj:74)
	at ring.middleware.session$session_response.invoke(session.clj:66)
	at ring.middleware.session$wrap_session$fn__24588.invoke(session.clj:109)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__24630.invoke(keyword_params.clj:36)
	at ring.middleware.nested_params$wrap_nested_params$fn__24688.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__24986.invoke(multipart_params.clj:173)
	at ring.middleware.params$wrap_params$fn__25010.invoke(params.clj:67)
	at ring.middleware.cookies$wrap_cookies$fn__24467.invoke(cookies.clj:175)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__25116.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource$fn__25026.invoke(resource.clj:37)
	at ring.middleware.content_type$wrap_content_type$fn__25064.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__25088.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__17997.invoke(not_modified.clj:53)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__23471.invoke(x_headers.clj:22)
```

When reaching the step of the callback URI.

I suspect associng the `access-token` to the session is the culprit.

### PR DESCRIPTION
**Pull request by gerdint**
Hopefully we can get this fix merged soonish, this is the 3rd PR regarding this.

The testing code changes are copied from PR #47, I hope @jamiepratt does not mind.

Requires Java 8 due to use of java.time.Instant in code for clarity

### CODE REVIEW

File: src/ring/middleware/oauth2.clj [hunk 1]
```diff
@@ -1,11 +1,12 @@
...
   (:require [clj-http.client :as http]
-            [clj-time.core :as time]
             [clojure.string :as str]
             [crypto.random :as random]
             [ring.util.codec :as codec]
             [ring.util.request :as req]
-            [ring.util.response :as resp]))
+            [ring.util.response :as resp])
+  (:import (java.time Instant)
+           (java.util Date)))
```
Comment (weavejester) [inline src/ring/middleware/oauth2.clj:9]: Can you use square brackets here, i.e.

```clojure
(:import [java.time Instant]
         [java.util Date])
```

**Review by weavejester — CHANGES_REQUESTED** [review]
Thanks for the PR. Just some minor formatting changes for consistency are required, plus changing the new function to private as its not part of the API.

Could you also change the commit message to:

    Replace clj-time with native java.time (fixes #27)

    Updates minimum required Java version to 8 due to use of java.time.Instant.

File: test/ring/middleware/oauth2_test.clj [hunk 2]
```diff
@@ -75,12 +74,12 @@
                          (assoc :session {::oauth2/state "xyzxyz"})
                          (assoc :query-params {"code" "abcabc", "state" "xyzxyz"}))
             response (test-handler request)
-            expires  (-> 3600 time/seconds time/from-now)]
+            expires  (#'oauth2/seconds-from-now-to-date 3600)]
```
Comment (weavejester) [inline test/ring/middleware/oauth2_test.clj:77]: Accessing a private var here saves a little code, but also ties the test case to the internals of the namespace being tested. Ideally we test only the public API. So instead, just inline the function:

```
            expires  (-> (Instant/now) (.plusSeconds 3600) (Date/from))
```

**Review by weavejester — CHANGES_REQUESTED** [review]
Almost there! Just one more change necessary to avoid tying the tests to private functions.

File: test/ring/middleware/oauth2_test.clj (hunk 2 above)
Comment (gerdint) [reply test/ring/middleware/oauth2_test.clj:77]: OK, though since identical code is used at four places in the test suite I might as well introduce a helper function for it in the tests I guess?

Comment (weavejester) [reply test/ring/middleware/oauth2_test.clj:77]: I don't think I mind. You could duplicate `seconds-from-now-to-date` in the test namespace if you wanted.

**Comment by jamiepratt** [comment]
Haven't had time to look at the code, but thanks for the work bringing it
up to par and merging this!

Jamie
--
*My homepage* <https://jamiep.org/> and *resume*
<https://www.jamiep.org/work/james-robert-pratt/>.
Phone no: *+48505206918 <https://wa.me/48505206918> (link messages me on
WhatsApp)*
Skype Name: *jamiepratt <https://join.skype.com/invite/ben7orDUhbwH>*

File: test/ring/middleware/oauth2_test.clj (hunk 2 above)
Comment (gerdint) [reply test/ring/middleware/oauth2_test.clj]: I did it the other way, see what you think.

Comment (weavejester) [reply test/ring/middleware/oauth2_test.clj]: That works, too. Can you ensure that the lines modified in ring.middleware.oauth are within 80 characters?

Comment (gerdint) [reply test/ring/middleware/oauth2_test.clj]: I believe the modified lines are all within 80 characters.

Comment (weavejester) [reply test/ring/middleware/oauth2_test.clj]: I think there's one line in your patch that might be 85?

**Comment by weavejester** [comment]
Looks good! Can you squash your commits, and it should be ready to merge.

File: test/ring/middleware/oauth2_test.clj (hunk 2 above)
Comment (gerdint) [reply test/ring/middleware/oauth2_test.clj]: As you perhaps noted the 2nd commit made that like shorter.

Comment (weavejester) [reply test/ring/middleware/oauth2_test.clj]: Oh, weird. Is the GitHub diff incorrect then? In any case, it looks like there are other lines over from previous commits, so I can always fix it with a later formatting commit. I just need the commits to be squashed down and then we're ready to merge.

**Comment by gerdint** [comment]
Squashed

**Comment by weavejester** [comment]
Thanks! Can you also fix the commit message? It has "Implement changes from review feedback" added to the end of it now.

**Comment by gerdint** [comment]
@weavejester Anything else?

**Comment by weavejester** [comment]
Nope! That's all good. Thanks for your work on this.

**Comment by gerdint** [comment]
@weavejester Good. Perhaps it would be worth making a 0.2.1 release with this fix since it seemed like a highly anticipated change.

**Comment by weavejester** [comment]
Released 0.2.1.
